export const teams = [
  { label: 'Blue'},
  { label: 'Red'}
]

export const regions = [
  { label: 'Global', value: 'ANY'},
  { label: 'NA' , value: 'NA1'},
  { label: 'EUW', value: 'EUW1'}
]

export const game_modes = [
  { label: 'Any', value: 'ANY'},
  { label: 'ARAM', value: 'ARAM'},
  { label: 'SR', value: 'CLASSIC'}
]

export const elos = [
  { label: 'All', value: ['ANY']},
  { label: 'Low', value: ['IRON','BRONZE','SILVER']},
  { label: 'Mid', value: ['GOLD', 'EMERALD','DIAMOND']},
  { label: 'High', value: ['MASTER', 'GRANDMASTER', 'CHALLENGER']},
]

export const versions = [
  { label: '14.14', value: '14-14'},
  { label: '14.13', value: '14-13'},
]

export const champions = [
  { label: 'Aatrox', value: 'Aatrox' },
  { label: 'Ahri', value: 'Ahri' },
  { label: 'Akali', value: 'Akali' },
  { label: 'Akshan', value: 'Akshan' },
  { label: 'Alistar', value: 'Alistar' },
  { label: 'Amumu', value: 'Amumu' },
  { label: 'Anivia', value: 'Anivia' },
  { label: 'Annie', value: 'Annie' },
  { label: 'Aphelios', value: 'Aphelios' },
  { label: 'Ashe', value: 'Ashe' },
  { label: 'Aurelion Sol', value: 'AurelionSol' },
  { label: 'Aurora', value: 'Aurora' },
  { label: 'Azir', value: 'Azir' },
  { label: 'Bard', value: 'Bard' },
  { label: `Bel'Veth`, value: 'Belveth' },
  { label: 'Blitzcrank', value: 'Blitzcrank' },
  { label: 'Brand', value: 'Brand' },
  { label: 'Braum', value: 'Braum' },
  { label: 'Briar', value: 'Briar' },
  { label: 'Caitlyn', value: 'Caitlyn' },
  { label: 'Camille', value: 'Camille' },
  { label: 'Cassiopeia', value: 'Cassiopeia' },
  { label: `Cho'Gath`, value: 'Chogath' },
  { label: 'Corki', value: 'Corki' },
  { label: 'Darius', value: 'Darius' },
  { label: 'Diana', value: 'Diana' },
  { label: 'Draven', value: 'Draven' },
  { label: 'Dr.Mundo', value: 'DrMundo' },
  { label: 'Ekko', value: 'Ekko' },
  { label: 'Elise', value: 'Elise' },
  { label: 'Evelynn', value: 'Evelynn' },
  { label: 'Ezreal', value: 'Ezreal' },
  { label: 'Fiddlesticks', value: 'FiddleSticks' },
  { label: 'Fiora', value: 'Fiora' },
  { label: 'Fizz', value: 'Fizz' },
  { label: 'Galio', value: 'Galio' },
  { label: 'Gangplank', value: 'Gangplank' },
  { label: 'Garen', value: 'Garen' },
  { label: 'Gnar', value: 'Gnar' },
  { label: 'Gragas', value: 'Gragas' },
  { label: 'Graves', value: 'Graves' },
  { label: 'Gwen', value: 'Gwen' },
  { label: 'Hecarim', value: 'Hecarim' },
  { label: 'Heimerdinger', value: 'Heimerdinger' },
  { label: 'Hwei', value: 'Hwei' },
  { label: 'Illaoi', value: 'Illaoi' },
  { label: 'Irelia', value: 'Irelia' },
  { label: 'Ivern', value: 'Ivern' },
  { label: 'Janna', value: 'Janna' },
  { label: 'Jarvan IV', value: 'JarvanIV' },
  { label: 'Jax', value: 'Jax' },
  { label: 'Jayce', value: 'Jayce' },
  { label: 'Jhin', value: 'Jhin' },
  { label: 'Jinx', value: 'Jinx' },
  { label: `Kai'sa`, value: 'Kaisa' },
  { label: 'Kalista', value: 'Kalista' },
  { label: 'Karma', value: 'Karma' },
  { label: 'Karthus', value: 'Karthus' },
  { label: 'Kassadin', value: 'Kassadin' },
  { label: 'Katarina', value: 'Katarina' },
  { label: 'Kayle', value: 'Kayle' },
  { label: 'Kayn', value: 'Kayn' },
  { label: 'Kennen', value: 'Kennen' },
  { label: `Kha'Zix`, value: 'Khazix' },
  { label: 'Kindred', value: 'Kindred' },
  { label: 'Kled', value: 'Kled' },
  { label: `Kog'Maw`, value: 'KogMaw' },
  { label: `K'Sante`, value: 'KSante' },
  { label: 'LeBlanc', value: 'Leblanc' },
  { label: 'Lee Sin', value: 'LeeSin' },
  { label: 'Leona', value: 'Leona' },
  { label: 'Lillia', value: 'Lillia' },
  { label: 'Lissandra', value: 'Lissandra' },
  { label: 'Lucian', value: 'Lucian' },
  { label: 'Lulu', value: 'Lulu' },
  { label: 'Lux', value: 'Lux' },
  { label: 'Malphite', value: 'Malphite' },
  { label: 'Malzahar', value: 'Malzahar' },
  { label: 'Maokai', value: 'Maokai' },
  { label: 'Master Yi', value: 'MasterYi' },
  { label: 'Milio', value: 'Milio' },
  { label: 'Miss Fortune', value: 'MissFortune' },
  { label: 'Mordekaiser', value: 'Mordekaiser' },
  { label: 'Morgana', value: 'Morgana' },
  { label: 'Naafiri', value: 'Naafiri' },
  { label: 'Nami', value: 'Nami' },
  { label: 'Nasus', value: 'Nasus' },
  { label: 'Nautilus', value: 'Nautilus' },
  { label: 'Neeko', value: 'Neeko' },
  { label: 'Nidalee', value: 'Nidalee' },
  { label: 'Nilah', value: 'Nilah' },
  { label: 'Nocturne', value: 'Nocturne' },
  { label: 'Nunu & Willump', value: 'Nunu' },
  { label: 'Olaf', value: 'Olaf' },
  { label: 'Orianna', value: 'Orianna' },
  { label: 'Ornn', value: 'Ornn' },
  { label: 'Pantheon', value: 'Pantheon' },
  { label: 'Poppy', value: 'Poppy' },
  { label: 'Pyke', value: 'Pyke' },
  { label: 'Qiyana', value: 'Qiyana' },
  { label: 'Quinn', value: 'Quinn' },
  { label: 'Rakan', value: 'Rakan' },
  { label: 'Rammus', value: 'Rammus' },
  { label: `Rek'Sai`, value: 'RekSai' },
  { label: 'Rell', value: 'Rell' },
  { label: 'Renata Glasc', value: 'Renata' },
  { label: 'Renekton', value: 'Renekton' },
  { label: 'Rengar', value: 'Rengar' },
  { label: 'Riven', value: 'Riven' },
  { label: 'Rumble', value: 'Rumble' },
  { label: 'Ryze', value: 'Ryze' },
  { label: 'Samira', value: 'Samira' },
  { label: 'Sejuani', value: 'Sejuani' },
  { label: 'Senna', value: 'Senna' },
  { label: 'Seraphine', value: 'Seraphine' },
  { label: 'Sett', value: 'Sett' },
  { label: 'Shaco', value: 'Shaco' },
  { label: 'Shen', value: 'Shen' },
  { label: 'Shyvana', value: 'Shyvana' },
  { label: 'Singed', value: 'Singed' },
  { label: 'Sion', value: 'Sion' },
  { label: 'Sivir', value: 'Sivir' },
  { label: 'Skarner', value: 'Skarner' },
  { label: 'Smolder', value: 'Smolder' },
  { label: 'Sona', value: 'Sona' },
  { label: 'Soraka', value: 'Soraka' },
  { label: 'Swain', value: 'Swain' },
  { label: 'Sylas', value: 'Sylas' },
  { label: 'Syndra', value: 'Syndra' },
  { label: 'Tahm Kench', value: 'TahmKench' },
  { label: 'Taliyah', value: 'Taliyah' },
  { label: 'Talon', value: 'Talon' },
  { label: 'Taric', value: 'Taric' },
  { label: 'Teemo', value: 'Teemo' },
  { label: 'Thresh', value: 'Thresh' },
  { label: 'Tristana', value: 'Tristana' },
  { label: 'Trundle', value: 'Trundle' },
  { label: 'Tryndamere', value: 'Tryndamere' },
  { label: 'Twisted Fate', value: 'TwistedFate' },
  { label: 'Twitch', value: 'Twitch' },
  { label: 'Udyr', value: 'Udyr' },
  { label: 'Urgot', value: 'Urgot' },
  { label: 'Varus', value: 'Varus' },
  { label: 'Vayne', value: 'Vayne' },
  { label: 'Veigar', value: 'Veigar' },
  { label: `Vel'Koz`, value: 'Velkoz' },
  { label: 'Vex', value: 'Vex' },
  { label: 'Vi', value: 'Vi' },
  { label: 'Viego', value: 'Viego' },
  { label: 'Viktor', value: 'Viktor' },
  { label: 'Vladimir', value: 'Vladimir' },
  { label: 'Volibear', value: 'Volibear' },
  { label: 'Warwick', value: 'Warwick' },
  { label: 'Wukong', value: 'MonkeyKing' },
  { label: 'Xayah', value: 'Xayah' },
  { label: 'Xerath', value: 'Xerath' },
  { label: 'Xin Zhao', value: 'XinZhao' },
  { label: 'Yasuo', value: 'Yasuo' },
  { label: 'Yone', value: 'Yone' },
  { label: 'Yorick', value: 'Yorick' },
  { label: 'Yuumi', value: 'Yuumi' },
  { label: 'Zac', value: 'Zac' },
  { label: 'Zed', value: 'Zed' },
  { label: 'Zeri', value: 'Zeri' },
  { label: 'Ziggs', value: 'Ziggs' },
  { label: 'Zilean', value: 'Zilean' },
  { label: 'Zoe', value: 'Zoe' },
  { label: 'Zyra', value: 'Zyra' }
]